### PR TITLE
Use local fetch

### PR DESCRIPTION
**Pull request by vecerek**
> BTW, the idea of providing a specific instance of fetch (the standard global one or a different implementation) is good and we could work on it.

https://github.com/contactlab/appy/issues/322#issuecomment-696758763

This PR takes the first step in removing the dependencies on globals, starting with `fetch`. Now all request methods return a function that takes `fetch` as an argument.

@StefanoMagrassi, what do you think?

### CODE REVIEW

**Comment by StefanoMagrassi** [comment]
@vecerek I was thinking about something less breaking:

```ts
export interface Fetch {
  (input: RequestInfo, init?: RequestInit): Promise<Response>;
}

export function getRequest(f: Fetch): Req<string> {
  return input => () => {
    const reqInput = normalizeReqInput(input);

    return f(...reqInput)
      .then(
        async response => {
          if (!response.ok) {
            throw toResponseError(
              new Error(
                `Request responded with status code ${response.status}`
              ),
              response
            );
          }

          const data = await response.text();

          return E.right({response, data});
        },
        e => {
          throw toRequestError(e, reqInput);
        }
      )
      .catch(e => E.left(e));
  };
}

export const request: Req<string> = getRequest(fetch); // <-- this is the global fetch
```

so the average user can keep using the library without changes and who needs a custom `fetch` function can use `getRequest()`.

The other combinators do not need to be changed because they already work with only `Req` type.

Tests also have to be modified:
```diff
// test/_setup.ts

import 'abort-controller/polyfill';
- import {fetch, Headers, Request, Response} from 'cross-fetch';
+ import {Headers, Request, Response} from 'cross-fetch';
+ import fetchMock from 'fetch-mock';

- (global as any).fetch = fetch;
+ (global as any).fetch = fetchMock.sandbox();
(global as any).Headers = Headers;
(global as any).Request = Request;
(global as any).Response = Response;
```
```diff
// test/index.spec.ts

import fetchMock from 'fetch-mock';
import {right, left} from 'fp-ts/lib/Either';
import * as appy from '../src/index';

+ const f = fetch as fetchMock.FetchMockSandbox;

afterEach(() => {
  - fetchMock.reset();
  + f.reset();
});

test('request() should return a right `Resp<string>` - default GET', async () => {
  const response = new Response('a list of resources', {
    status: 200,
    headers: {}
  });

- fetchMock.mock('http://localhost/api/resources', response);
+ f.mock('http://localhost/api/resources', response);

  const r = await appy.request('http://localhost/api/resources')();

  expect(r).toEqual(right({response, data: 'a list of resources'}));
});

// ... and so on
```

This solution has 2 main drawbacks:
- `RequestInfo`, `RequestInit` and `Response` types (used in our `Fetch` definition) are still defined in the Typescript's `lib.dom.ts` standard library, so a potential "only Nodejs" user would have to add the `dom` lib to its own `tsconfig.json`;
- the `getRequest()` function should be moved to a separated file (different from the main `appy` module) in order to avoid any kind of error in case the global `fetch` is not defined

**Comment by vecerek** [comment]
@StefanoMagrassi, that makes a lot of sense! I applied your suggestion in https://github.com/contactlab/appy/pull/325/commits/a7ea2d2a682d28f068f2495d65b02182c8156ca1 and split the index file into several smaller ones. Let me know if you'd like to see a different logical grouping of the functions/types in those files 🙂 I'll have to look up how to:

> add the `dom` lib to its own `tsconfig.json`

**Comment by StefanoMagrassi** [comment]
mmmm... @vecerek I do not really like this kind of separation into "micro" modules... I think that the types declaration and the `makeRequest()` function should be tied together in one file and then imported where needed.
I would also not change so much the `index.ts`.

Apart from these consideration, I would let you think more about the goal of your PR... `appy` is a wrapper for the Fetch API and uses extensively all the other related objects/classes/APIs (like `Request`, `Response`, `Header` etc.)
So, maybe, this is not the right solution in the you have to work with multiple environments that do not support it...

**Comment by vecerek** [comment]
Closing this PR since I started pursuing a different approach to solving the issue originally mentioned in the [linked issue](https://github.com/contactlab/appy/issues/322#) around building service-specific client libraries. Decided to instead create HTTP client-agnostic implementations. Thanks, Stefano, for all the feedback 🙂

**Pull request closed without merging**
